skip_parameters = [
  "% Solids (Generated Monthly-MOR)",
  "Qty Wet Sludge Disposed",
  "Qty Wet Sludge Generated",
  "Volatile Solids Reduction Waste Sludge to Disposal",
  "Weight of Sludge(Dry) Disposed",
  "Weight of Sludge(Dry) Generated",
  "% VOL. RED.",
  "Cake Dry Tons/Day",
  "Dissolved O2 - North",
  "Dissolved Oxygen, Effluent",
  "Dissolved Oxygen, Influent",
  "Flow(MAX), Influent",
  # "Flow, Effluent",
  # "Flow, Influent",
  "Hours Bypassed",
  "Peracetic Acid",
  # "pH - Effluent (Max)",
  # "pH - Effluent (Min)",
  # "pH - Influent",
  "Pounds of Chlorine - Effluent",
  "Pounds of Sulfur Dioxide - Effluent",
  "Rainfall",
  "Temperature - DIG.SDG.",
  # "Temperature - Effluent",
  # "Temperature - Influent",
  # "Temperature - North",
  "Wet Cake",
  "% Volatile Suspended Solids",
  # "Total Suspended Solids",
  # "TSS - Change in Wt",
  "Volatile Suspended Solids",
  # "Biochemical Oxygen Demand",
  "Dissolved Oxygen",
  # "pH",
  "Sample Amount",
  "Settleable Solids",
  "Sulfur",
  "Ammonia as N",
  # "Chemical Oxygen Demand",
  # "Soluble BOD",
  "Organic Nitrogen",
  "Total Nitrogen",
  "Phosphorus-total",
  "LC50 Static 48Hr Acute Ceriodaphnia",
  "LC50 Static 48Hr Acute Pimephales",
  "Total Alkalinity (as CaCO3)",
  "Calcium",
  "Hardness",
  "Magnesium",
  "Arsenic",
  "Cadmium",
  "Chromium",
  "Cobalt",
  "Copper",
  "Lead",
  "Analysis Date/Time",
  "Mercury",
  "Method Reference",
  "Subcontract Lab ID",
  "Molybdenum",
  "Nickel",
  "Selenium",
  "Zinc",
  "Oil and Grease (HEM)",
  "Volatile Acids",
  "SARS-COV2"
]
